specVersion: 1.0.0

name: subquery
version: 0.0.1
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your
  Cosmos (Cronos) based SubQuery project via the Etheruem API"
repository: "https://github.com/subquery/cosmos-subql-starter/tree/main/Cronos/\
  cronos-evm-starter-via-eth"
schema:
  file: ./schema.graphql
network:
  chainId: "25"
  # This endpoint must be a public non-pruned archive node
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # Take a look here for some Cronos endpoints https://moonflow.solutions/rpc-servers
  # Free endpoint is:
  endpoint: "https://evm.cronos.org/"
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: "https://api.subquery.network/sq/subquery/cosmos-cronos-dictionary"
dataSources:
  - kind: ethereum/Runtime
    startBlock: 1 # Block that this contract was created
    options:
      abi: erc20
      address: "0x2D03bECE6747ADC00E1a131BBA1469C15fD11e03" # Wrapped CRO https://cronos.org/explorer/address/0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23
    assets:
      erc20:
        file: "erc20.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        # Using block handlers slows your project down as they can be executed with each and every block. Only use if you need to
        # - handler: handleBlock
        #   kind: ethereum/BlockHandler
        # Here is a basic Transaction handler, not used in this example 
        # - handler: handleTransaction
        #   kind: ethereum/TransactionHandler
        #   filter:
        #     ## The function can either be the function fragment or signature
            ## https://docs.ethers.io/v5/api/utils/abi/fragments/#FunctionFragment
            # function: '0x095ea7b3'
            # function: '0x7ff36ab500000000000000000000000000000000000000000000000000000000'
            # function: approve(address guy, uint256 wad)
        # Here is a basic Transfer event handler
        - handler: handleLog
          kind: ethereum/LogHandler
          filter:
            topics:
              # The topics filter follows the Ethereum JSON-PRC log filters
              # https://docs.ethers.io/v5/concepts/events
              # Example valid values:
              # - '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
              # - Transfer(address,address,u256)
              # - Transfer(address src, address dst, uint256 wad)
              - "Transfer(address indexed from, address indexed to, uint256 value)"
              - null
              - null
              - null
